application: fsndp4
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/spi/.*
  script: main.API_APP

- url: /crons/send_reminder
  script: main.WEB_APP

- url: .*
  script: main.WEB_APP


libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: 1.0
